### ISSUE TITLE
Adding Bootstrap 4.3.1

### ISSUE THREAD

**Issue by hersel91** [gamingtalker/gamingtalker-vanilla-theme#1]
https://getbootstrap.com/docs/4.3/getting-started/introduction/

**Comment by mirkobrombin** [comment]
No sense overloading the layout with frameworks.

**Comment by hersel91** [comment]
> No sense overloading the layout with frameworks.

It makes sense since it's his first time, better to use protection. With Bootstrap CDN you don't overload anything, just insert the links to the CDN.

**Comment by mirkobrombin** [comment]
This is not the right method.

> > No sense overloading the layout with frameworks.
> 
> It makes sense since it's his first time, better to use protection. With Bootstrap CDN you don't overload anything, just insert the links to the CDN.
